### ISSUE TITLE
Keyboard layout problems

### ISSUE THREAD

**Issue by massimobio** [89netraM/ordne#1]
Should it have been called Wördle 😂?

Some of the keys are cut off on iPhone 13 / iOS 15 / Safari:
![IMG_271A3308A031-1](https://user-images.githubusercontent.com/240599/149828231-0a2b65e9-4c60-4806-93c8-cdf245b447ee.jpeg)

**Comment by 89netraM** [comment]
Oh no, the iPhone must be too tall and not wide enough. I'll look into it tomorrow. Thanks for the heads up.

**Comment by 89netraM** [comment]
Should be fixed now. Might take a little while before the update is live. Please let me know if this doesn't fix it.
